### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#1809]
We should be sure that PYBOSSA follows new GDPR law. This article includes [some items](https://techblog.bozho.net/gdpr-practical-guide-developers/) that we must ensure are available within PYBOSSA:

- [x] [Forget me](https://github.com/Scifabric/pybossa/issues/1810)
- [x] [Notify 3rd parties for erasure](https://github.com/Scifabric/pybossa/issues/1811)
- [x] [Restrict processing](https://github.com/Scifabric/pybossa/issues/1812)
- [x] [Export data](https://github.com/Scifabric/pybossa/issues/1813)
- [x] Allow users to edit their profile 
- [x] Consent checkboxes
- [x] See all my data (via Export data)
- [x] [Age checks](https://github.com/Scifabric/pybossa/issues/1814)
- [x] Keeping data for no longer than necessary
- [x] [Unsubscribe users from contributed projects](https://github.com/Scifabric/pybossa/issues/1826)
- [x] [Anonymize IPs for anon users](https://github.com/Scifabric/pybossa/issues/1827)

**Comment by teleyinex** [comment]
See all my data and Keeping data for no longer than necessary are under discussion. The first one is a sub-set of Export data, and as stated in the article it's not mandatory. This one will be very difficult when you have thousands of projects, as your data could vary a lot.

Regarding keeping data for no longer than necessary: The purpose of PYBOSSA is to do open science. So data should be kept for analysis almost forever. However, the only link between the contributed taskruns and personal data of user's is their ID, so maybe we should create a random identifier for each registered user (not linked to a foreign key) that will ensure that we can delete the user's without any problems without affecting the task_runs. Any feedback on this is more than welcome.

**Comment by teleyinex** [comment]
Done!
